trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)' # Tag unik berdasarkan ID build
  repository: 'todo-apps-devops' # Nama image lokal

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: Build
    displayName: Build Docker Image
    pool:
      vmImage: ubuntu-latest
    steps:
    # Langkah 1: Build Docker image
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/backend/Dockerfile' # Sesuaikan jalur jika berbeda
        tags: |
          $(repository):$(tag)
