# version: '3.8'
services:
  frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Enable polling for better file watching in Docker
    volumes:
      - .:/app  # Mount the frontend directory
      - frontend_node_modules:/app/node_modules  # Named volume for node_modules
    command: npm run dev  # Assuming you have a dev script with hot reload

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:h2:tcp://localhost:9092/sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  frontend_node_modules:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: