services:
  app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NOD_ENV: development
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
           - node_modules
        - action: rebuild
          path: package.json

  be:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NOD_ENV: development
    develop:
      watch:
        - action: sync
          ignore:
           - node_modules
        - action: rebuild
          path: package.json