  # version: '3.8'
  services:
    frontend:
      restart: always
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - '3000:3000'
      environment:
        - NODE_ENV=development
        - CHOKIDAR_USEPOLLING=true  # Enable polling for better file watching in Docker
      volumes:
        - .:/app  # Mount the frontend directory
        - frontend_node_modules:/app/node_modules  # Named volume for node_modules
      command: npm run dev  # Assuming you have a dev script with hot reload

  volumes:
    frontend_node_modules: