version: '3.8'
services:
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Enable polling for better file watching in Docker
    volumes:
      - ./frontend:/app  # Mount the frontend directory
      - frontend_node_modules:/app/node_modules  # Named volume for node_modules
    develop:
      watch:
        - action: sync+restart
          path: ./frontend/src
          target: /app/src
          ignore:
            - node_modules/
            - build/
            - '*.test.tsx'
        - action: rebuild
          path: ./frontend
          target: package.json
    command: npm run dev  # Assuming you have a dev script with hot reload

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app  # Mount the backend directory
      - backend_node_modules:/app/node_modules  # Named volume for node_modules
    develop:
      watch:
        - action: sync+restart
          path: ./backend/src
          target: /*
          ignore:
            - node_modules/
            - dist/
            - '*.test.js'
        - action: rebuild
          path: ./backend
          target: package.json
    command: npm run dev  # Assuming you have a dev script with hot reload

volumes:
  frontend_node_modules:
  backend_node_modules: