name: Code Check
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    name: â¬£ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ Checkout repo
        uses: actions/checkout@v4

      - name: âŽ” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: ðŸ“¥ Download deps
        run: npm install --frozen-lockfile

      - name: ðŸ”¬ Lint
        run: npm run lint
typecheck:
  name: Ê¦ TypeScript
  runs-on: ubuntu-latest
  steps:
    - name: â¬‡ Checkout repo
      uses: actions/checkout@v4

    - name: âŽ” Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: ðŸ“¥ Download deps
      run: npm install --frozen-lockfile

    - name: ðŸ”Ž Type check
      run: npm run typecheck
prettier:
  name: ðŸ’… Prettier
  runs-on: ubuntu-latest
  steps:
    - name: â¬‡ Checkout repo
      uses: actions/checkout@v4

    - name: âŽ” Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: ðŸ“¥ Download deps
      run: npm install --frozen-lockfile

    - name: ðŸ”Ž Type check
      run: npm run format
