name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  SonarCloudScan:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args: >
              -Dsonar.projectKey=todo-apps-devops
              -Dsonar.organization=jhoniananta
  test:
    needs: SonarCloudScan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Set up Node.js version
      uses: actions/setup-node@v2
      with:
        node-version: ${{matrix.node-version}}
    - name: Install dependencies
      working-directory: ./
      run: npm install  

    - name: Test Eslint Check
      working-directory: ./
      run: npm run lint

  build-and-deploy-using-docker:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

        # Build and push Container image from docker to Azure Container Registry
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: acrcloudtodoapps.azurecr.io
          username: ${{ secrets.REGISTERY_USERNAME }}
          password: ${{ secrets.REGISTERY_PASSWORD }}

      - name: Build and push docker image
        run: |
          docker build --build-arg VITE_BASE_URL=${{secrets.BASE_URL_ENDPOINT}} . -t acrcloudtodoapps.azurecr.io/myapp:${{ github.sha }}
          docker push acrcloudtodoapps.azurecr.io/myapp:${{ github.sha }}
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'todo-apps-frontend'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'acrcloudtodoapps.azurecr.io/myapp:${{ github.sha }}'